image: julia:0.7

before_script:
  - apt-get update && apt-get -y install make g++
  - julia -e "using Pkg; Pkg.develop(PackageSpec(url=pwd()))"

testjob:
  script:
    - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.test("KalmanFilter", coverage=true);
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'
